/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#00522b",
        "on-tertiary-fixed-variant": "#93000b",
        "on-secondary-fixed": "#00210e",
        "on-tertiary-container": "#ffb5ad",
        "primary": "#00453d",
        "on-secondary-container": "#00743f",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#a8f0e3",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "surface-dim": "#dadada",
        "tertiary-container": "#a90c12",
        "primary-container": "#075e54",
        "tertiary": "#7f0008",
        "surface-tint": "#1c695f",
        "secondary": "#006d3b",
        "inverse-primary": "#8cd4c7",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdad6",
        "secondary-fixed": "#8df9b0",
        "outline-variant": "#bec9c5",
        "on-primary-fixed-variant": "#005047",
        "on-error": "#ffffff",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#ffb4ab",
        "surface-container-high": "#e8e8e8",
        "inverse-on-surface": "#f0f1f1",
        "error": "#ba1a1a",
        "on-primary-container": "#8dd5c8",
        "outline": "#6f7976",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#3f4946",
        "surface-container": "#eeeeee",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#8cd4c7",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#410002",
        "surface-container-low": "#f3f3f4",
        "secondary-container": "#8df9b0",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#00201c",
        "secondary-fixed-dim": "#71dc96",
        "background": "#f9f9f9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 24px 24px -4px rgba(26,28,28,0.06)",
        "ambient-up": "0 -8px 32px -4px rgba(26,28,28,0.08)",
        float: "0 8px 32px rgba(26,28,28,0.12)",
      },
    },
  },
  plugins: [],
};
